### ISSUE TITLE
Increase custom script name length to 60 characters

### ISSUE THREAD

**Issue by syntrydy** [GluuFederation/oxCore#105]
# Description

Increase custom script name length to 60 characters

**Comment by willow9886** [comment]
We should add a note in the docs that specifies this character limit for the interception scripts. cc @shmorri

**Comment by shmorri** [comment]
Added:
https://github.com/GluuFederation/docs-ce-prod/blob/3.1.5/docs/source/admin-guide/custom-script.md#script-naming
