### ISSUE TITLE
Couchbase : shortcut our existing keys to increase performance and save space

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxCore#140]
Right now our schema keys are quite long. We have to introduce mapping table which will re-map our schema key and push to couchbase shorter version of our schema keys.

Here we defined rules by which our shortcuter will work :
https://github.com/GluuFederation/oxCore/wiki/Couchbase-key-mappings

Examples (it may look weird until you look to wiki) :
`oxAuthUserId` -> `_uId`, 
`oxAuthUserDN` -> `_uDN`
`oxAuthDefaultAcrValues` -> `_dAcrValues`

Task consist of two parts:

1. introduce shortcuter - > Yuriy Z
2. inject it into Couchbase mapper -> Yura M

**Comment by yuriyz** [comment]
@shmorri can we transfer our wiki page to docs somewhere in couchbase related pages ?

**Comment by shmorri** [comment]
I’ll get it transferred over.

**Comment by shmorri** [comment]
https://github.com/GluuFederation/docs-cb-prod/blob/4.0/docs/source/keymappings.md

**Comment by yuriyz** [comment]
Implemented in 4.0. We have both shortcut and reverse operation to correctly map it back into ORM objects.
