### ISSUE TITLE
N1QL filters not using numeric types correctly

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/oxCore#146]
A SCIM search like
```
SearchRequest sr=new SearchRequest();
sr.setFilter("urn:ietf:params:scim:schemas:extension:gluu:2.0:User:scimCustomThird eq 1 and displayName eq \"test\" ");
```

where `scimCustomThird` is a custom attribute registered as numeric.

oxtrust.log showing:

```
2019-09-11 21:02:03,522 INFO] [gluu.oxtrust.service.antlr.scimFilter.FilterListener] 
(FilterListener.java:159) - LDAP filter expression computed was 
(&(displayName=test)(scimCustomThird=1))
```

The last line is the output of a call to org.gluu.search.filter.Filter.toString() on the filter built.

the N1QL generated as shown in oxtrust_persistence.log looks this way:

```
SELECT gluu_doc.*, dn 
FROM `gluu_user` AS gluu_doc 
WHERE ( ( objectClass = "gluuPerson" ) AND 
( ( displayName = "test" ) OR ( "test" IN displayName ) ) 
AND 
( ( scimCustomThird = "1" ) OR ( "1" IN scimCustomThird ) ) ) 
ORDER BY displayName LIMIT 200 OFFSET 0
```

It is not understanding that scimCustomThird is actually a number

**Comment by yurem** [comment]
Please provide filter and bean examples

**Comment by yurem** [comment]
Checked. It works well. For example ORM generates:
```
( ( objectClass = "gluuPerson" ) AND age >= 16 )
```

ORM client code should use in filter integer type instead string becuase Couchbase schema-less.

**Comment by jgomer2001** [comment]
right
