### ISSUE TITLE
Usage of IN produces inaccurate queries

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/oxCore#151]
Suppose I have one user in Couchbase looking like

```
{ ...
  scimCustomThird: 3000,
   ...
}
```

and I want to retrieve users having `scimCustomThird` greater than 2999

I create a filter this way:

```
String attribute = "scimCustomThird";
Integer objValue = Integer.valueOf(2999);
Filter.createANDFilter(
    Filter.createNOTFilter(Filter.createEqualityFilter(attribute, objValue)),
    Filter.createGreaterOrEqualFilter(attribute, objValue))
```

oxtrust_persistence.log shows:

```
TRACE [qtp392292416-11] [org.gluu.persist.couchbase.impl.CouchbaseEntryManager] (CouchbaseEntryManager.java:435) - Search filter: (&(&(objectClass=gluuPerson))(&(!(scimCustomThird=2999))(scimCustomThird>=2999)))
DEBUG [qtp392292416-11] [gluu.persist.couchbase.operation.impl.CouchbaseOperationsServiceImpl] (CouchbaseOperationsServiceImpl.java:501) - Ignoring scope 'SUB for expression: ( ( objectClass = "gluuPerson" ) AND ( ( NOT ( ( scimCustomThird = 2999 ) OR ( 2999 IN scimCustomThird ) ) ) AND scimCustomThird >= 2999 ) )
DEBUG [qtp392292416-11] [gluu.persist.couchbase.operation.impl.CouchbaseOperationsServiceImpl] (CouchbaseOperationsServiceImpl.java:545) - Execution query: 'SELECT gluu_doc.*, dn FROM `gluu_user` AS gluu_doc WHERE ( ( objectClass = "gluuPerson" ) AND ( ( NOT ( ( scimCustomThird = 2999 ) OR ( 2999 IN scimCustomThird ) ) ) AND scimCustomThird >= 2999 ) ) LIMIT 200 OFFSET 0'
```

The N1QL query generated was

```
SELECT gluu_doc.*, dn 
FROM `gluu_user` AS gluu_doc 
WHERE (     
	( objectClass = "gluuPerson" ) 
	AND 
	(
		(NOT (  
		      ( scimCustomThird = 2999 ) 
			OR ( 2999 IN scimCustomThird )
		      ) 
		)     		
    		AND     		
    		scimCustomThird >= 2999 
    	) 
) 
```

But the result set returned is empty. When dropping `OR ( 2999 IN scimCustomThird )` it works as expected.

`(2999 IN scimCustomThird)` evaluates `null` in the case of the sample user which makes the whole WHERE evaluate to `null`.

In general `false OR null`, `null OR fase`, `true AND null`, `null AND true`, `NOT null` all evaluate `null`.

From what I see, IN is useful when the property is really an array (`"property": [ ... ]`), not a simple value (`"property": value`).

**Comment by yurem** [comment]
Is it regarding custome attributes?

Couchbase uses `IN` for multi valued attributes. It determines attribute type based on bean annotation. In case with custom attributes it cant do this. But in this case you can specify information about attribute via Filter.

Can you try this?
```
String attribute = "scimCustomThird";
Integer objValue = Integer.valueOf(2999);
Filter.createANDFilter(
    Filter.createNOTFilter(Filter.createEqualityFilter(attribute, objValue).notMultiValued()),
    Filter.createGreaterOrEqualFilter(attribute, objValue))
```

**Comment by yurem** [comment]
I added notMultiValued in this commit https://github.com/GluuFederation/oxCore/commit/0d68d730123e0020bc49115a8c72a8b5ef487363

**Comment by yurem** [comment]
@jgomer2001 please, reopen it if needed

**Comment by jgomer2001** [comment]
I tried the following using latest oxcore jars:

`Filter.createEqualityFilter("scimCustomThird", 2999).notMultiValued()`

but still producing

`( ( objectClass = "gluuPerson" ) AND ( ( scimCustomThird = 3000 ) OR ( 3000 IN scimCustomThird ) ) )`

Similar thing using other data types, eg:

`Filter.createEqualityFilter("givenName", "a").notMultiValued()`

outputs

`( ( objectClass = "gluuPerson" ) AND ( ( givenName = "a" ) OR ( "a" IN givenName ) ) `

actually calling `notMultiValued` should not be necessary because by default `multiValued  = false` in Filter class.

**Comment by yurem** [comment]
Current code do next conversions:
`Filter.createEqualityFilter("scimCustomThird", 2999).notMultiValued();`
-->
`scimCustomThird = 2999`

`Filter.createEqualityFilter("scimCustomThird", 2999).multiValued()`
-->
`2999 IN scimCustomThird`

`Filter.createEqualityFilter("scimCustomThird", 2999);`
-->
`( ( scimCustomThird = 2999 ) OR ( 2999 IN scimCustomThird ) )`
