### ISSUE TITLE
Create API for Persistence Tier

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxCore#161]
From a deploment perspective, it would be better if we isolated the code that performs the persistence. This way, it can be scaled more efficiently from a microservice perspective.

**Comment by yurem** [comment]
We have already independent modules:
- `persistence-annotation` -- Persistence annotations only
- `persistence-model` -- Base DB models which not depend on specifc DB
- `persistence-core` -- Base DB classes which not depend on specific DB
- `persistence-cdi` -- Services for injection in CDI based applications
- `persistence-standalone` -- Factories for not CDI applications
- `persistence-filter` -- Gluu filtering API which specifc DB implementation convert to N1QL, LDAP filter, etc..
- `persistence-ldap/persistence-couchbase/persistence-hybrid` -- Implementations for specifc DB
- `persistence-ldap-sample/persistence-couchbase-sample` --  Samples
