### ISSUE TITLE
Server do wrong redirects when oxAuth/oxTrust is behind LB

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxCore#168]

**Comment by mzico** [comment]
@yurem : here are two txt files attached. 

- One: when authentication going through Load balancer ( which is failing ) [ [through_lb.txt](https://github.com/GluuFederation/oxCore/files/3918264/through_lb.txt) ] 
- Second: when authentication going to Gluu server directly ( no LB and it's working ).  [ [directly_Gluu_server.txt](https://github.com/GluuFederation/oxCore/files/3918265/directly_Gluu_server.txt) ]

**Comment by yurem** [comment]
It's Jetty bug. jetty-distribution-9.4.19.v20190610 not work correctly with proxy X-Forwarded-XYZ headers.

Steps to fix it in CE:
1. Log into CE
2. Stop all jetty services: oxauth/identity/etc..
3. `cd /opt/jetty-9.4`
4. `wget https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-distribution/9.4.24.v20191120/jetty-distribution-9.4.24.v20191120.tar.gz`
5. `tar -xzf 9.4.24.v20191120/jetty-distribution-9.4.24.v20191120.tar.gz`
6. `rm -f 9.4.24.v20191120/jetty-distribution-9.4.24.v20191120.tar.gz`
7. `rm -f /opt/jetty`
8. `ln -s /opt/jetty-9.4/jetty-distribution-9.4.24.v20191120 /opt/jetty`
9. Start required jetty services

**Comment by XertroV** [comment]
For anyone else finding this issue (I was being redirected to the internal IP), if the reverse-proxy is transparent it doesn't seem to happen.
