### ISSUE TITLE
Why encodeTime/decodeTime in PersistenceEntryManager need baseDN ?

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/oxCore#183]
Here: 
https://github.com/GluuFederation/oxCore/blob/master/persistence-core/src/main/java/org/gluu/persist/PersistenceEntryManager.java#L88-L89

Concrete entry managers (ldap/cb/hybrid) simply ignore this parameter (baseDN/primarykey)

We can remove it if unnecessary. If that's the case, these couple of methods look suspicious too:
https://github.com/GluuFederation/oxAuth/blob/master/common/src/main/java/org/gluu/oxauth/service/UserService.java#L450-L460 ...

**Comment by yurem** [comment]
Our persistence layer supports Hybrid type. Also LDAP and CB expects date in different formats. As result we need dynamically determine which persistence mechanism are we using  to properly format date. That's why DN is needed. Here are methods in LDAP and CB pesristence modules for comparison:
```
// LDAP
    @Override
    public String encodeTime(String baseDN, Date date) {
        if (date == null) {
            return null;
        }

        return com.unboundid.util.StaticUtils.StaticUtils.encodeGeneralizedTime(date);
    }

CB:
    @Override
    public String encodeTime(String baseDN, Date date) {
        if (date == null) {
            return null;
        }

        SimpleDateFormat jsonDateFormat = new SimpleDateFormat(JSON_DATA_FORMAT);
        return jsonDateFormat.format(date);
    }
```

**Comment by jgomer2001** [comment]
I didn't understand :) , `baseDN` is unused in the 3 encodeTime methods

**Comment by jgomer2001** [comment]
@yurem ^^^^

**Comment by yurem** [comment]
https://github.com/GluuFederation/oxCore/blob/b6ca1929c91d937f1b5ff681551fbae4a46f832c/persistence-hybrid/src/main/java/org/gluu/persist/hybrid/impl/HybridEntryManager.java#L177

**Comment by jgomer2001** [comment]
ugh... I need (more) glasses. Thank you
