### ISSUE TITLE
Permission denied error when deleting TR

### ISSUE THREAD

**Issue by uboznikov** [GluuFederation/oxCore#19]
```
 ERROR [org.gluu.oxtrust.ldap.service.LdifArchiver] Failed to write into log file
java.io.FileNotFoundException: /var/ox/identity/removed/inum=@!885E.6825.A923.E96E!0002!3820.0E68!0006!50E0.82D6,ou=trustRelationships,inum=@!885E.6825.A923.E96E!0002!3820.0E68,ou=appliances,o=gluu1483453611032 (Permission denied)
```

**Comment by nynymike** [comment]
Ganesh--I wonder if this is because the file is not owned by the right user. Can you check community-edition-setup. There is a section where we set the correct ownership for each folder.

**Comment by ganesh-at-wiw** [comment]
May I know which OS/Server is facing the trouble in particular?
In the meantime I'm checking my local VM.

**Comment by ganesh-at-wiw** [comment]
From setup.py, I see that /var/ox is owned by tomcat.


>         self.oxBaseDataFolder = "/var/ox"
>         self.run(['/bin/chown', '-R', 'tomcat:tomcat', self.oxBaseDataFolder])
> 

To investigate further I need the server where this is being faced.

**Comment by yurem** [comment]
@ganesh-at-wiw I think you are checking installer from 3.0.0
In my 3.0.0 Beta2 installation there are no problem with owner:
```
ls -l1 /var/ox/identity/
total 8
drwxr-xr-x 2 root gluu 4096 Jan  4 09:19 cr-snapshots
drwxr-xr-x 2 root gluu 4096 Jan  4 09:19 removed
```

```
cat /etc/group | grep gluu
gluu:x:1000:ldap,jetty,node
```

There is only problem with permissions. Going to fix this.
