### ISSUE TITLE
Redis sentinel provider pool exhaustion

### ISSUE THREAD

**Issue by kepuss** [GluuFederation/oxCore#190]
Hi @yuriyz @yurem 

I have been performance testing redis sentinel configuration of Gluu and it was hanging indefinitely.
I checked threads and they were hanging on 
at redis.clients.util.Pool.getResource(Pool.java:50)

I configured the setMaxWaitMillis (it would be good to make it configurable from UI), which stopped the waiting behaviour but the result was the pool exhaustion.
Similar to the issue here: https://github.com/xetorthio/jedis/issues/2098

So I looked through your implementation and your RedisSentinelProvider is not releasing the resources back to pool.

I did a simple fix where I wrapped all put,get,remove with try-with-resources and it works correctly now.
Example:
```
    @Override
    public void put(String key, Object object) {
        try(Jedis client = pool.getResource()) {
            String status = client.set(key.getBytes(), SerializationUtils.serialize((Serializable) object));
            LOG.trace("put - key: " + key + ", status: " + status);
        }
    }
```

**Comment by yuriyz** [comment]
@kepuss Thanks for reporting it, fixed in 4.2. Also feel free to open PR.
