### ISSUE TITLE
 Lowercase filter for multivalued attribute produces wrong query in CB

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/oxCore#197]
Suppose the filter

```
Filter.createEqualityFilter(Filter.createLowercaseFilter("attribute"), "123456789").multiValued(true)
```

it produces `WHERE ( ( objectClass = "gluuPerson" ) AND "123456789" IN null )`

With `.multiValued(false)` it works better: `WHERE ( ( objectClass = "gluuPerson" ) AND LOWER("attribute") = "123456789")`

**Comment by yurem** [comment]
How do you get result N1QL? Is it from working code or from test?

**Comment by yurem** [comment]
Fixed. Now it poduces:

```
1) expression: ( ( objectClass = "gluuPerson" ) AND ANY uid_ IN uid SATISFIES LOWER(uid_) = "admin" END )

2) expression: ( ( objectClass = "gluuPerson" ) AND ANY uid_ IN uid SATISFIES uid_ = "admin" END )
```
