### ISSUE TITLE
Fix method to update log level

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxCore#204]
After log4j libs update we get this message with same count loggers:
```
2020-09-24 09:40:32,078 INFO  [Thread-313] [org.gluu.service.logger.LoggerService] (LoggerService.java:165) - Updated log level of '131' loggers to TRACE
```

It should updae only newly created loggers. Now it seems do update all loggers all the rime

**Comment by syntrydy** [comment]
Customer also complaining about it, i guess we can move all log lines of loggerService from INFO to DEBUG

**Comment by yurem** [comment]
Fixed, @syntrydy Can you check if new implementation conforms customers expectations
