### ISSUE TITLE
Redis: update jedis library and add ssl support for cluster provider.

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxCore#215]
Tried to connect to Redis cluster using ssl connection (updated Cache Provider Configuration in UI). I've also examined the source code and it seems that:

Currently in Gluu version 4.2.1 jedis library is used in version 2.10.2
- According to Jedis support ssl connection with the cluster is available from jedis version 3.1.0 https://github.com/redis/jedis/issues/2175#issuecomment-608990019
- According to Gluu source code currently ssl communication is only available with Redis Standalone. https://github.com/GluuFederation/oxCore/blob/a32b14a5a2b72f3640a30b3ab66bfc2af433b458/core-cache/src/main/java/org/gluu/service/cache/RedisStandaloneProvider.java#L37

Proposed enhancements:
- Update Jedis client version to 3.1.0 or above.
- Upgrade RedisClusterProvider in oxCore to enable such communication.

Support: 9550

**Comment by lukaszgolinski** [comment]
Hello,

What is the status of this enhancement?
We are would like to use SSL communication with Redis Cluster in our application.

Best regards,
Lukasz Golinski

**Comment by yuriyz** [comment]
Status is "on hold". For support questions/issues open ticket on https://support.gluu.org/

**Comment by moabu** [comment]
Issue has been prioritized by [request](https://support.gluu.org/other/10131/cloud-native-cn-edition-423-aws-elasticache-redis-service-access-via-ssl/)

**Comment by yuriyz** [comment]
@Milton-Ch is checking it.

**Comment by moabu** [comment]
after @Milton-Ch confirms it working in 4.3.1 we will attempt to back port it to 4.2.3.

**Comment by Milton-Ch** [comment]
We updated Jedis lib to version 3.7.0, it allows us to handle SSL connection properly with Redis using Standalone, Cluster and Sentinel providers.
All changes were merged into `master` and `version_4.2.3.sp2` branches.
