### ISSUE TITLE
feat(document-store): add support to categorize files

### ISSUE THREAD

**Issue by iromli** [GluuFederation/oxCore#244]
In cloud-native edition, we have usecase where container need to pull certain files from DB document store. It would be nice document store provides a way to distinguish/categorize files, i.e. files for shibboleth, files for casa, and so on.

One way I can think of right now is using tags/labels where it may have 1 or more values, i.e. `tags=oxshibboleth` or `tags=oxauth,casa` (the files are shared by multiple Gluu components). But we can discuss about the design here.

**Comment by shekhar16** [comment]
We already added a attribute for categorization i.e. oxModuleProperty., we can add the category at the time of insertion.
Like oxtrust, oxauth etc.

**Comment by iromli** [comment]
@shekhar16 good to know.

I tested DB store to get Shibboleth config files generated by oxTrust UI. 

Here's an example of entry:

```
inum: b73aea0b-223e-424f-9855-2cd7ce25b17f                                                                                                            
objectClass: oxDocument                                                                                                                               
objectClass: top                                                                                                                                      
oxEnabled: true                                                                                                                                       
oxModuleProperty: oxtrusr server       
```

I see that oxModuleProperty value is `oxtrusr server` (perhaps typo?). 

Anyway, does `oxModuleProperty` support multivalues (in non-LDAP persistence)? As mentioned above, one specific usecase is that Shibboleth config files stored in DB store should be categorized as shibboleth (and oxtrust optionally) so we can search and/or filter which files should be pulled into docker container.

**Comment by shekhar16** [comment]
@iromli  yes oxModuleProperty supports  multivalues

**Comment by shekhar16** [comment]
Code has been merged, closing this ticket.
