### ISSUE TITLE
Generalized time could not be searched in OpenLDAP

### ISSUE THREAD

**Issue by uboznikov** [GluuFederation/oxCore#27]
A compound search query with generalized time returns 0 results:

`(&(birthdate>=2014-01-01)(oxTrustExternalId=*2*))`

![generalized-time-0-results](https://cloud.githubusercontent.com/assets/16329085/22427562/a7e932ce-e73e-11e6-9803-2854bbf83848.png)

This same search query has been originally working in OpenDJ.

[PersonFiltersMainTests.java](https://github.com/GluuFederation/SCIM-Client/blob/master/src/test/java/gluu/scim/client/PersonFiltersMainTests.java#L51)

**Comment by nynymike** [comment]
what is the LDAP syntax in the schema for birthdate?

**Comment by uboznikov** [comment]
[gluu.schema:](https://github.com/GluuFederation/community-edition-setup/blob/master/static/openldap/gluu.schema#L2237-L2242)

```
attributetype ( oxAttribute:326 NAME 'birthdate'
	DESC 'Birthday of the person, represented as an ISO 8601:2004 [ISO8601‑2004] YYYY-MM-DD format'
	ORDERING generalizedTimeOrderingMatch
	EQUALITY generalizedTimeMatch
	SYNTAX 1.3.6.1.4.1.1466.115.121.1.24
	X-ORIGIN 'OpenID Connect 1.0 Standard Claim' )
```

[101-ox.ldif:](https://github.com/GluuFederation/community-edition-setup/blob/master/static/opendj/deprecated/101-ox.ldif#L1909-L1914)

```
attributeTypes: ( 1.3.6.1.4.1.48710.1.3.326 NAME 'birthdate'
  DESC 'Birthday of the person, represented as an ISO 8601:2004 [ISO8601‑2004] YYYY-MM-DD format'
  ORDERING generalizedTimeOrderingMatch
  EQUALITY generalizedTimeMatch
  SYNTAX 1.3.6.1.4.1.1466.115.121.1.24
  X-ORIGIN 'OpenID Connect 1.0 Standard Claim' )
```

**Comment by nynymike** [comment]
`2014-02-10` does not look like it's the right format. I'd expect it to look something like

**Comment by yurem** [comment]
Yes, I saw the same behavior. OpenDJ can do search by dateTime fields even that they are defined as string. OpenLDAP is more strict. As result I fixed attribute type in our schema to allow do search.

**Comment by yurem** [comment]
@uboznikov you can use these method to prepare data in right format:

ldapEntryManage.encodeGeneralizedTime/decodeGeneralizedTime

or

com.unboundid.util.StaticUtils.decodeGeneralizedTime(date)/decodeGeneralizedTime...

**Comment by uboznikov** [comment]
I have modified the format but still it can't be searched.

![generalized-time-modified](https://cloud.githubusercontent.com/assets/16329085/22509534/6918354a-e8c9-11e6-9691-d121c3604a40.png)

Can somebody test this with `ldapsearch`? Thanks.

**Comment by uboznikov** [comment]
@yurem The code is using `StaticUtils.decodeGeneralizedTime` and `StaticUtils.encodeGeneralizedTime`:

[GluuCustomAttribute.java](https://github.com/GluuFederation/oxTrust/blob/master/server/src/main/java/org/gluu/oxtrust/model/GluuCustomAttribute.java#L95-L120)

Just need to update the test data:

[scim-test-data.ldif](https://github.com/GluuFederation/community-edition-setup/blob/master/templates/test/scim-client/data/scim-test-data.ldif#L109)

**Comment by nynymike** [comment]
Can you try to search using `ldapsearch` versus java please?

**Comment by yurem** [comment]
On ce-dev:
```
 /opt/opendj/bin/ldapsearch -h localhost -p 1636 -Z -X -D "cn=directory manager" -j /tmp/.dspw -b 'o=gluu' -T '(birthdate>=20130922093600.263Z)' dn
dn: inum=@!5A58.AE0D.D383.1E46!0001!E38B.7DBE!0000!XXXX.AAAA.2222,ou=people,o=@!5A58.AE0D.D383.1E46!0001!E38B.7DBE,o=gluu
```

**Comment by uboznikov** [comment]
[- Fix date format](https://github.com/GluuFederation/community-edition-setup/commit/b13568de9dbc99633eba40f94b494f5054ffc0d7)

[- Fix date format](https://github.com/GluuFederation/SCIM-Client/commit/82d8ce71bcce6b365d906a5fa1ccf8c30cc500ff)
