### ISSUE TITLE
Create generic CacheService (without dependencies to ehcache)

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxCore#28]
Create generic CacheService (without dependencies to ehcache)

Think about region concept. E.g. in memcached does not have regions however it contains built-in expiration.

**Comment by willow9886** [comment]
@yuriyz still working on this? Will it make it into 3.1.2?

**Comment by yuriyz** [comment]
@willow9886 It nice to have and will allow to remove ugly code from apps that are using cache service (e.g. oxauth). However it is not critical. Let make it if we will have some spare time.

**Comment by yuriyz** [comment]
done in master. oxtrust and oxauth code is adapted.
