### ISSUE TITLE
Memcached provider should read configuration file with expiration setting for each region

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxCore#30]
The problem that by default we put all objects in cache with expiration time 1 day.

We need to improve [MemcachedProvider](https://github.com/GluuFederation/oxCore/blob/master/oxService/src/main/java/org/xdi/service/cache/MemcachedProvider.java) to put objects into cache with configurable lifetime per Region.

We can store each region setting in MemcachedConfiguration or inside war file in file in similar to EhCache way..

**Comment by yuriyz** [comment]
Moved to oxauth https://github.com/GluuFederation/oxAuth/issues/477

**Comment by yuriyz** [comment]
We also need to cover this first https://github.com/GluuFederation/oxCore/issues/28
