### ISSUE TITLE
Use org.gluu.site.ldap.persistence.BatchOperation in oxCore LdapEntryManager(AbstractEntryManager)

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxCore#39]
There is one issue with LDAP pagination which we found half year ago. In pagination we must use same LDAP connection during iteration through pages. For this we implemented BatchOperation. We need to update LdapEntryManager(AbstractEntryManager) to use BatchOperation. Without this some processes like CR which uses pagination get periodically:
```
Caused by: com.unboundid.ldap.sdk.LDAPSearchException: paged results cookie is invalid
        at com.unboundid.ldap.sdk.LDAPConnection.search(LDAPConnection.java:3648)
```

**Comment by worm333** [comment]
In [this commit](https://github.com/GluuFederation/oxCore/pull/40) I've modified [search](https://github.com/GluuFederation/oxCore/blob/82c36b7decfb1f2b42f8f6aeb0162ba78ff6a617/oxLdap/src/main/java/org/gluu/site/ldap/OperationsFacade.java#L195) method to use single ldap connection. It will prevent `com.unboundid.ldap.sdk.LDAPSearchException: paged results cookie is invalid`
