### ISSUE TITLE
Invalid Timestamp Generated by org.gluu.saml.AuthRequest

### ISSUE THREAD

**Issue by teemuk** [GluuFederation/oxCore#4]
When integrating Gluu SAML Jython interceptor with simpleSAMLphp, an error is returned by simpleSAMLphp when it tries to parse the SAML timestamp of the authentication request:

```
May 10 08:43:29 simplesamlphp ERROR [3898ebcd7a] Caused by: Exception: Invalid SAML2 timestamp passed to parseSAML2Time: 2016-05-10T5:43:39
...
```

This is caused by the org.gluu.saml.AuthRequest using following timestamp format:

```
private static final SimpleDateFormat simpleDataFormat = new SimpleDateFormat("yyyy-MM-dd'T'H:mm:ss");
```

This can be fixed by replacing the simpleDateFormat with following:

```
private static final SimpleDateFormat simpleDataFormat = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss'Z'");
```

This was tested with Gluu version 2.4.3.

**Comment by nynymike** [comment]
https://github.com/GluuFederation/oxCore/commit/858e65575e84a9b879895eecc5ab9ae6a4647316
