### ISSUE TITLE
Support Couchbase

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxCore#57]
Current Gluu version supports only LDAP as persistent mechanism. We need to add support for additional types of persistent storage.

Here are initial steps how to do this:
1. Add new library oxFilter to oxCore to allow remove direct dependency in oxAuth/oxTrust/etc to UnboundId SDK filter classes.
2. Improve oxLdap to support oxFilter instead of UnboundID SDK filter
3. Replace in oxAuth/oxTrust and other projects UnboundID SDK filter with oxCore Filters

Add new configuration files:
1. Add new properties file ox.properties. The purpose of this file to specify type of persistent storage. Also it should contains application specific setting which mandatory for all applications.

**Comment by yurem** [comment]
In our persistence layer we uses generic java interface javax.persistence.EntityManager . Our LdapEntryManager extends it. I think we need to follow same rule in all other persistence mechanism.
These steps we need to do next:
1. Extract all CRUD methods which we uses in LdapEntryManager into interface. Current LdapEntryManager should implements it.
2. Create ox-couchbase.json or ox-couchbase.properties. I think it's better to use json becuase we might need to provide some mappingm extra configs, etc..
create factory like 'CacheProviderFactory' which uses CDI to create right instance of EntryManger
3. Implement CouchbaseEntryManager.

**Comment by yurem** [comment]
The main part is done. oxCouchbase implements CouchbaseEntryManager which has same base interface with LdapEntryManager. Now we need to try to run oxAuth/oxTrust with this new persistence machanism.

This is rest of tasks from which we need to implement:
1.  oxCouchbase should support LDAP CRYPT and SHA authentication mechanism #77 
2. oxCouchbase should use SSL to connect server #78
3. Update oxAuth/oxTrust to use oxLdap/oxCouchbase #79
