### ISSUE TITLE
Remove ou=appliances, o=orgInum and replace orgInum/appliacne Inum with UUID

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxCore#67]
![image](https://user-images.githubusercontent.com/3717101/36436431-d4c2b584-1629-11e8-853f-61f41a4e8977.png)

It would be better if `ou=appliances,o=gluu` was instead `ou=appliances,o=(org-inum),o=gluu`

**Comment by yurem** [comment]
We need to do:

    Remove o=orgInum node
    Remove ou=appliances node
    Remove inum=applianceInum node under ou=appliances
    Move all nodes which we store inside 1+2+3 to previous node.

**Comment by yurem** [comment]
Implemented
