### ISSUE TITLE
Sorting in operations facade is operating upon an empty list, not actual result set

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/oxCore#68]
Some context info:
https://github.com/GluuFederation/oxTrust/issues/394#issuecomment-270396330
https://github.com/GluuFederation/oxCore/commit/305d9eaecc5139b96889620e2395bda499ed2678
https://github.com/GluuFederation/oxCore/commit/8dd8541aa98464e0ddc081674e6581dfa2af7c87

In [this line](https://github.com/GluuFederation/oxCore/blob/version_3.1.3/oxLdap/src/main/java/org/gluu/site/ldap/OperationsFacade.java#L386) of OperationsFacade, the sorting is carried out upon `searchResultEntries`, which is an empty list. The sorting needs to be performed on `resultSearchResultEntries`, but this is a unmodifiable list according to  impl of method `getSearchEntries` of ldap-sdk, thus it throws me:

```
Caused by: java.lang.UnsupportedOperationException
	at java.util.Collections$UnmodifiableList.sort(Collections.java:1331) ~[?:1.8.0_65]
	at java.util.Collections.sort(Collections.java:175) ~[?:1.8.0_65]
	at org.gluu.site.ldap.OperationsFacade.sortListByAttributes(OperationsFacade.java:718) ~[oxcore-ldap-3.1.3-SNAPSHOT.jar:?]
	at org.gluu.site.ldap.OperationsFacade.searchSearchResult(OperationsFacade.java:386) ~[oxcore-ldap-3.1.3-SNAPSHOT.jar:?]
	at org.gluu.site.ldap.persistence.LdapEntryManager.findEntriesSearchSearchResult(LdapEntryManager.java:448) ~[oxcore-ldap-3.1.3-SNAPSHOT.jar:?]
```

We need to rewrite method `sortListByAttributes` of `OperationsFacade` to sort properly and efficiently, and also introduce a `sortOrder` parameter of type `org.xdi.ldap.model.SortOrder`. This is needed for SCIM service impl. Currently in `searchSearchResult` the `sortOrder` is being ignored.

**Comment by jgomer2001** [comment]
@yurem I pushed a candidate solution in branch [issue_68](https://github.com/GluuFederation/oxCore/tree/issue_68), but concluded that implementing a comparator such as [SearchResultEntryComparator](
https://github.com/GluuFederation/oxCore/blob/version_3.1.3/oxLdap/src/main/java/org/gluu/site/ldap/OperationsFacade.java#L721)
does not help because in [this block](https://github.com/GluuFederation/oxCore/blob/version_3.1.3/oxLdap/src/main/java/org/gluu/site/ldap/OperationsFacade.java#L766-L776) there is no successful match since values belong to `com.unboundid.ldap.sdk.Attribute` class, not to `String` or `Date` as desired.

I wonder if ldapsdk does not actually offer a way to output the results already sorted, instead sorting manually...

if not, we might resort to passing as an additional parameter the Class associated to the sorting attribute from oxtrust scim code.

**Comment by yurem** [comment]
There is no ready to use solution to do LDAP server side sort. OpenDJ supports only VLV. But there is big problem with them. We need to prepare all VLV search indexes before hand. If there is small difference in filter at runtime LDAP will not use it. In SCIM we can't prepare this list.

In method which call sort there is typo in parameter name. I fixed [this](https://github.com/GluuFederation/oxCore/commit/38fddcbaf315e6bdd4abccb2f45020706cd383ce). But we need to check. Probably we need to clone this list if SDK returns unmodifiable list.

Regarding lines which you mentioned in Compactor, yes, we can remove them. It's limited copy of [this ](https://github.com/GluuFederation/oxCore/blob/master/oxPersist/src/main/java/org/gluu/persist/impl/BaseEntryManager.java#L1678) comparator in EntryManager

**Comment by jgomer2001** [comment]
@yurem One flaw of server side sorting strategy is that results follow a relative order, not absolute. And this is no good, but it seems we have no choice.

Example:

say we have 9 people with an integer attribute called "amount". Assume the following was the output of a search with
	
	startIndex=1
	count=9

`(user_1, 20), (user_2, 30), (user_3, 40), (user_4, 60), (user_5, 50), (user_6, 10), (user_7, 70), (user_8, 90), (user_9, 80)`

think of `(uid, amount)` pairs.

So when running a search with 

	startIndex=1
	count=9
	sortBy=amount
	
the following will be the output:

`(user_6, 10), (user_1, 20), (user_2, 30), (user_3, 40), (user_5, 50), (user_4, 60), (user_7, 70), (user_9, 80), (user_8, 90)`


If we try with:
	
	startIndex=1
	count=5
	sortBy=amount
	
we will get

`(user_1, 20), (user_2, 30), (user_3, 40), (user_5, 50), (user_4, 60)`

In order words, a portion of the first sample list was sorted.

instead I would like to see

`(user_6, 10), (user_1, 20), (user_2, 30), (user_3, 40)`

which is based on an absolute sorting

**Comment by yurem** [comment]
Can you explain why you expect to see first result entry (user_6, 10) ?
In your search you used `startIndex=1`. Can you try to do the same with `startIndex=0`?

**Comment by jgomer2001** [comment]
... I was just assuming the scim convention of using 1-based indexing in this case.
I'll close this issue as 3.2 will brings us better sorting capabilities
