### ISSUE TITLE
Add new CacheProvider to store data in LDAp under ou=session

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxCore#83]
In 4.0 we added Couchbase support. It allows to store specific portion of data in Memcached. Hence there is no sense to use external Memcahed, Redis, etc in case if organization selected to use Couchbase. We need additional CacheProvider which should store data under ou=sessions.

**Comment by yuriyz** [comment]
I propose to put it under ou=cache since we put in cache not only sessions but many other entities.

**Comment by afroDC** [comment]
> Hence there is no sense to use external Memcahed, Redis, etc

This could cause issues as memcached is not clusterable/replicatable. So for full redundancy you would still need to fall back to redis-cluster or utilize couchbase for cache, tokens and session data.

**Comment by yurem** [comment]
We did this in 3.1.4 already
